version: 2
updates:
  - package-ecosystem: "pip"
    directory: "."
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      pip:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: ".github/"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      gha:
        patterns:
          - "*"
