name: e2e

on:
  pull_request:
    branches: [master]

jobs:
  e2e:
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-python@v4.6.1
        with:
          python-version: "3.11.0"
          cache: pip
      - run: python -m pip install -r requirements.txt
      - run: python -m pytest
