name: CI

on:
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [macos-15, ubuntu-24.04, windows-2025]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.13.0'
          cache: pip
      - if: matrix.os == 'ubuntu-24.04'
        uses: awalsh128/cache-apt-pkgs-action@v1.5.1
        with:
          packages: libegl1
          version: 1.0
      - run: python -m pip install -r requirements.txt
      # - run: python -m pylint ./**/*.py
      - run: python -m pytest
